[defaults]
format = "{time}\n"
paused_state_text = "paused"
resumed_state_text = "resumed"
[[sessions]]
id = "5"
name = "5"
duration = "5m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "10"
name = "10"
duration = "10m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "15"
name = "15"
duration = "15m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "20"
name = "20"
duration = "20m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "25"
name = "25"
duration = "25m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "30"
name = "30"
duration = "30m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "35"
name = "35"
duration = "35m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "40"
name = "40"
duration = "40m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "45"
name = "45"
duration = "45m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "50"
name = "50"
duration = "50m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "55"
name = "55"
duration = "55m"
time_format = "%M:%S"
command = "notify-send 'Done!'"
[[sessions]]
id = "60"
name = "60"
duration = "60m"
time_format = "%M:%S"
command = "notify-send 'Done!'"


