[mgr]
prepend_keymap = [
    { on = [ "g", "S" ],       run = "cd ~/26_Freshman_Spring",   desc = "Go to current Semester" },
    { on = [ "g", "m" ],       run = "cd ~/Music/navidrome",   desc = "Go to Navidrome Music Folder" },
    { on = [ "g", "p" ],       run = "cd ~/Music/navidrome/playlists",   desc = "Go to Navidrome Playlists Folder" },
]
