[mgr]
prepend_keymap = [
    { on = [ "g", "D" ],       run = "cd ~/Documents",   desc = "Go to ~/Documents" },
    { on = [ "g", "S" ],       run = "cd ~/Documents/School/CMU/26_Summer",   desc = "Go to current Semester" },
    { on = [ "g", "m" ],       run = "cd ~/Music/navidrome",   desc = "Go to Navidrome Music Folder" },
    { on = [ "g", "b" ],       run = "cd ~/Documents/books",   desc = "Go to books folder" },
    { on = [ "g", "n" ],       run = "cd '/home/maxlang/Documents/IGB Lab/NMRs/'",   desc = "Go to NMRs folder" },
    { on = [ "g", "t" ],       run = "cd '/home/maxlang/.local/share/Trash'",   desc = "Go to Trash" },

    { on = [ "<Enter>" ], run = [ "open" ], desc = "Open and exit" },
    { on = [ "R" ], run = 'shell --block "ya emit rename; zeditor -n --wait bulk-rename.txt"', desc = "Bulk rename with Zed" }
]
