[manager]
show_hidden = true
ratio = [1,2,2]
[opener]
  zed = [
    { run = 'zeditor --wait "$@"', block = true, for = "unix" },
    # { run = '"C:\Program Files\Zed\zed.exe" %*', block = true, for = "windows" }, #Example windows
  ]
  gimp = [
    { run = 'gimp "$@"', orphan = true, for = "unix" },
    # { run = '"C:\Program Files\GIMP 2\bin\gimp-2.10.exe" %*', orphan = true, for = "windows" }, #Example windows
  ]
  obsidian = [
    { run = 'obsidian "$@"', orphan = true, for = "unix" },
    # { run = '"C:\Program Files\GIMP 2\bin\gimp-2.10.exe" %*', orphan = true, for = "windows" }, #Example windows
  ]
  open = [
    { run = 'xdg-open "$@"', desc = "Open", for = "unix" }
  ]

[open]
prepend_rules = [
  { name = "*.txt", use = "zed" },
  { name = "*.json", use = "zed" },
  { name = "*.lock", use = "zed" },
  { name = "*.jsonc", use = "zed" },
  { name = "*.toml", use = "zed" },
  { name = "*.py", use = "zed" },
  { name = "*.html", use = "zed" },
  { name = "*.nix", use = "zed" },
  { name = "*.conf", use = "zed" },
  { name = "*.txt", use = "zed" },
  { name = "*.md", use = "obsidian" },
  { name = "*.png", use = "gimp" },
  { name = "*.jpg", use = "gimp" },
  { name = "*.jpeg", use = "gimp" },
  { name = "*.gif", use = "gimp" },
  { name = "*.svg", use = "gimp" },
  { name = "*", use = "open" } # Fallback to xdg-open for everything else
]