[mgr]
show_hidden = false
ratio = [1,2,2]
sort_by = "mtime"

[opener]
  zed = [
    { run = 'zeditor -n --wait %s', orphan = true, for = "unix" },
  ]
  gimp = [
    { run = 'gimp %s', orphan = true, for = "unix" },
  ]
  obsidian = [
    { run = 'obsidian %s', orphan = true, for = "unix" },
  ]
  pymol = [
    { run = 'pymol %s', orphan = true, for = "unix" },
  ]
  okular = [
    { run = 'okular %s', orphan = true, for = "unix" },
  ]
  open = [
    { run = 'xdg-open %s', desc = "Open", for = "unix" }
  ]

[open]
prepend_rules = [
  { url = "*.txt", use = "zed" },
  { url = "*.json", use = "zed" },
  { url = "*.lock", use = "zed" },
  { url = "*.jsonc", use = "zed" },
  { url = "*.toml", use = "zed" },
  { url = "*.py", use = "zed" },
  { url = "*.html", use = "zed" },
  { url = "*.nix", use = "zed" },
  { url = "*.conf", use = "zed" },
  { url = "*.txt", use = "zed" },
  { url = "*.md", use = "obsidian" },
  { url = "*.png", use = "gimp" },
  { url = "*.jpg", use = "gimp" },
  { url = "*.jpeg", use = "gimp" },
  { url = "*.gif", use = "gimp" },
  { url = "*.svg", use = "gimp" },
  { url = "*.pse", use = "pymol" },
  { url = "*.pdf", use = "okular" },
  { url = "*.pub", use = "zed" },
  { url = "*", use = "open" } # Fallback to xdg-open for everything else
]
