# .sops.yaml — recipients/creation rules for sops. Safe to commit (PUBLIC keys only).

keys:
  - &primary age17p9rfxqmxdscf2n0v5eadht43u03z3vxsg6vtqum4v23y002rs6swyex3k
creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
    - age:
      - *primary
